name: JD-DailyBonus

on:
  schedule:
    - cron: "0-3 16 * * *"
  watch:
    types: started

jobs:
  checkin:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Get js file
      run: |
        wget -O ./jd.js https://raw.githubusercontent.com/NobyDa/Script/master/JD-DailyBonus/JD_DailyBonus.js
        sed -i "s#var Key = ''#var Key = \'${{ secrets.JD_COOKIE }}\'#" jd.js
     
    - name: Install module
      run: npm install request

    - name: Start checkin
      run: node jd.js >> result.log

    - name: Push notification
      run: |
        curl -X POST https://sc.ftqq.com/${{ secrets.SC_KEY }}.send -d "text=JD-DailyBonus&desp=`cat result.log`"