name: Panel-DailyBonus

on:
  schedule:
    - cron:  0 2 * * *

jobs:
  checkin:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: init
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Checkin
      run: |
        python3 checkin.py <<EOF
        ${{secrets.PANEL_SITE}}
        ${{secrets.PANEL_USER}}
        ${{secrets.PANEL_PWD}}
        ${{secrets.SC_KEY}}
        EOF